### PR TITLE
Add google colab inference demo

### PR DESCRIPTION
**Pull request by mahdilamb**

### CODE REVIEW

**Comment by shensheng272** [comment]
Hi, thanks for demo. How about adding the links to the Third-party resources in README ?
Like https://github.com/meituan/YOLOv6/pull/288

**Comment by mahdilamb** [comment]
I've update that now

**Comment by shensheng272** [comment]
Hi，could you add short description and move to the **Third-party resources**  part in README
Also "inference.ipynb" should be removed because link is enough.
Thanks

**Comment by mahdilamb** [comment]
Have done :D

**Pull request merged**
