### PR TITLE
Feature: Added camera support for realtime Object Detection

### PR DESCRIPTION
**Pull request by d4rk-lucif3r**
Video support from @1chimaruGin

Tutorial

Just give source = 'camera'

python tools/infer.py --weights yolov6/weights/yolov6t.pt --source camera

The file will be saved as camera.mp4

### CODE REVIEW

**Comment by Chilicyy** [comment]
Thanks for your attention! It'll be appreciated that you can add this feature based on our latest code, because we have updated some relevant scripts to fit different data formats.

**Comment by Chilicyy** [comment]
Thanks for your attention! It'll be appreciated that you can add this feature based on our latest code, because we have updated some relevant scripts to fit different data formats.

**Comment by d4rk-lucif3r** [comment]
Yes I've taken the lates code only

**Comment by d4rk-lucif3r** [comment]
@Chilicyy Updated the branch again

**Pull request closed without merging**
